### PR TITLE
Add basic Chinese support

### PR DESCRIPTION
**Pull request by astropeak**
Hi,

I added basic support for Chinese. This modification is straightforward since the code already supports Japanese.

The word tokenizer is provided by jieba, a widely used one for Chinese word segmentation.

I found the stopwords list at
https://raw.githubusercontent.com/6/stopwords-json/master/dist/zh.json

I only tried it a little, but the results seem quite good.

### CODE REVIEW

**Comment by miso-belica** [comment]
Thanks a lot :)

**Comment by ArtificialNotImbecile** [comment]
This only works on `--url` but when I used it in `--file_path` option, it returns nothing.

**Comment by miso-belica** [comment]
@ArtificialNotImbecile Hi, that's sad. Can you please report and issue with URL and commands which is working and attached file and command which is not?

**Comment by ArtificialNotImbecile** [comment]
@miso-belica  I can not reproduce my bug, so it most likely my environment has some problem. I just update my Ubuntu 16.04 today and it works perfectly fine for both Chinese and English in both `--url` and `--file_path` :)

**Pull request merged**
