### PR TITLE
Keep compatible with pycountry >= 18.5.27 

### PR DESCRIPTION
**Pull request by ivanprado**
Since pycountry 18.5.27 language lookup retuns None when key not found (see: https://bitbucket.org/flyingcircus/pycountry/commits/72b1927b3cb9bfd81b547244eefc45395e23f9b8 ). As result sumy breaks. This fix the issue by checking if the returned value is None.

### CODE REVIEW

**Comment by ivanprado** [comment]
Travis has failed, but it seems that it is not related with my changes:

```
no such option: --use-wheel
The command "pip install -U --use-wheel pytest pytest-cov" failed and exited with 2 during .
```

**Comment by ivanprado** [comment]
@miso-belica done! It now fails for python 3.3 as it states python 3.4 is required. See: https://travis-ci.org/miso-belica/sumy/jobs/480795037

Should I do something?

**Comment by miso-belica** [comment]
@ivanprado Thank you very much. Especially for your patience :)

**Comment by ivanprado** [comment]
@miso-belica thank you very much for you speed merging that :-)

**Pull request merged**
