### PR TITLE
Greek stemmer bug fix

### PR DESCRIPTION
**Pull request by NC0DER**
Greetings,

As mentioned in issue #173 I added a test to reproduce the empty stem bug of the greek stemmer.
I committed the test case first as to reproduce the bug, and then in the next commit I added the bug fix.

If you got any feedback, please let me know.

Thank you for your time.

### CODE REVIEW

**Comment by miso-belica** [comment]
@NC0DER can you please allow me to update your PR? There should be checkbox for it. I need to rebase the branch on main. Or please rebase it.

**Comment by NC0DER** [comment]
@miso-belica I found the checkbox titled _"Allow edits by maintainers"_ and enabled this setting. Sorry for this inconvenience. If anything else is required, please let me know.

**Comment by miso-belica** [comment]
I had to remove Python v3.5 from CI. But it is [dead](https://dev.to/misobelica/python-features-by-version-3318) anyway.

**Review by miso-belica — APPROVED** [review]
Thank you 👍

**Pull request merged**
